name: Run Sauce Labs Tests

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip3 install selenium requests

      - name: Run Sauce Labs tests
        env:
          SAUCE_USERNAME: ${{ Sauce.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ Sauce.SAUCE_ACCESS_KEY }}
        run: python3 simple_chrome_test.py

